robot_reach_study_node:
  ros__parameters:

    # moveit stuff
    planning_group: "manipulator"
    fixed_frame: "base_link"
    object_frame: "reach_object"
    tool_frame: "tcp"

    # pcd stuff
    pcd_package: "reach_demo"
    pcd_filename_path: "config/part.pcd"

    # average neighbor calc
    get_avg_neighbor_count: false

    # invert orientation of normals
    invert_z_tool_rotation: false

    # db comparison
    compare_dbs: [ "" ]

    # database stuff
    config_name: "demo_config"
    results_package: "reach_demo"
    results_directory: "results"

    # initial seed state for ik solver
    initial_seed_state: [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 ]

    # to do path generation or not
    generate_paths: true
    # set if path_generation_config.initial_source_robot_configurations is true
    # when existing database is not needed -> source is defined in yaml file by robot configs
    generate_paths_only: false

    visualize_results: true
    keep_running: true
    run_initial_study_only: false

    optimization:
      radius: 0.2
      max_steps: 10
      step_improvement_threshold: 0.01

    ik_solver_config:
      name: "moveit_reach_plugins/ik/MoveItIKSolver"
      tool_frame: "tcp"
      distance_threshold: 0.0
      planning_group: "manipulator"
      collision_mesh_package: "package://reach_demo/config/part.ply"
      collision_mesh_filename_path: "config/part.ply"
      collision_mesh_frame: "reach_object"
      touch_links: [""]
      evaluation_plugin:
        name: "reach_core/plugins/MultiplicativeFactory"
        plugins: ["moveit_reach_plugins/evaluation/ManipulabilityMoveIt", "moveit_reach_plugins/evaluation/DistancePenaltyMoveIt"]
        moveit_reach_plugins/evaluation/ManipulabilityMoveIt:
          planning_group: "manipulator"
        moveit_reach_plugins/evaluation/DistancePenaltyMoveIt:
          planning_group: "manipulator"
          distance_threshold: 0.025
          exponent: 2
          collision_mesh_package: "package://reach_demo/config/part.ply"
          collision_mesh_filename_path: "config/part.ply"
          collision_mesh_frame: "reach_object"
          touch_links: [""]

    display_config:
      name: "moveit_reach_plugins/display/MoveItReachDisplay"
      planning_group: "manipulator"
      collision_mesh_package: "package://reach_demo/config/part.ply"
      collision_mesh_filename_path: "config/part.ply"
      collision_mesh_frame: "reach_object"
      fixed_frame: "base_link"
      marker_scale: 0.05

    path_generation_config:

      # one planning group for all path generation plugins
      planning_group: "manipulator"
      fixed_frame: "base_link"

      # initial sources are mutually exclusive
      initial_source_db: true     # false
      # if db_goals_are_start is false, goals from db will be goals in planning
      # and start state has to be set in yaml file:
      # db_goals_are_start: false
      db_goals_are_start: false
      start_state:
        name: "start_state.yaml"
        package: "reach_demo"
        directory: "config"

      db:
        config_name: "demo_config"
        package: "reach_demo"
        directory: "results"
        name: "path_optimized_reach.db"

      initial_source_robot_configurations: false  # true
      robot_configurations:
        name: "source.yaml"
        package: "reach_demo"
        directory: "config"

      collision_mesh_package: "package://reach_demo/config/part.ply"
      collision_mesh_frame: "reach_object"

      path_plugins:
        - path_00
#        - path_0
        - path_1
#        - path_2
        - path_3
      #        - path_4

      path_00:
        plugin_name: "moveit_reach_plugins/path/FreeSpacePathGeneration"
        # end_state is not used when db_goals_are_start==false for first trajectory generation
        # (e.g if FreeSpacePathGeneration was path_1)
#        end_state:
#          joint_b: -1.7278759594743864
#          joint_e: -0.017453292519943295
#          joint_l: 1.3264502315156903
#          joint_r: 1.2217304763960306
#          joint_s: 1.204277
#          joint_t: 0.40142572795869574
#          joint_u: 1.7627825445142729
        # global and tool transformations are used when no end_state is defined
        # nor is db_goals_are_start==false
        global_transformation:
          tx: 0.0
          ty: 0.0
          tz: 0.0
          rx: 0.0   #deg
          ry: 0.0  #deg
          rz: 0.0    #deg
        tool_transformation:
          tx: 0.0
          ty: 0.0
          tz: 0.0
          rx: 0.0   #deg
          ry: 0.0  #deg
          rz: 0.0    #deg
        touch_links: [ "" ]
        display_motion_plans: false
        publish_planning_requests: false
        num_planning_attempts: 10
        max_velocity_scaling_factor: 1.0
        max_acceleration_scaling_factor: 0.1
        allowed_planning_time: 10.0
        goal_joint_tolerance: 0.0001
        goal_position_tolerance: 0.0001
        goal_orientation_tolerance: 0.0001
        poses_frame_id: "base_link"
        pipeline_name: "ompl"
        planner_id: "RRTConnect"
#        pipeline_name: "pilz_industrial_motion_planner"
#        planner_id: "LIN"
        planning_group: "manipulator"
        tool_frame: "tcp"
        distance_threshold: 0.0

      path_0:
        plugin_name: "moveit_reach_plugins/path/FreeSpacePathGeneration"
        # end_state is not used when db_goals_are_start==false for first trajectory generation
        # (e.g if FreeSpacePathGeneration was path_1)
#        end_state:
#          joint_b: -1.7278759594743864
#          joint_e: -0.017453292519943295
#          joint_l: 1.3264502315156903
#          joint_r: 1.2217304763960306
#          joint_s: 1.204277
#          joint_t: 0.40142572795869574
#          joint_u: 1.7627825445142729
        # global and tool transformations are used when no end_state is defined
        # nor is db_goals_are_start==false
        global_transformation:
          tx: 0.0
          ty: 0.0
          tz: 0.1
          rx: 0.0   #deg
          ry: 0.0  #deg
          rz: 0.0    #deg
        tool_transformation:
          tx: 0.0
          ty: 0.0
          tz: -0.2
          rx: 0.0   #deg
          ry: 0.0  #deg
          rz: 0.0    #deg
        touch_links: [ "" ]
        display_motion_plans: false
        publish_planning_requests: false
        num_planning_attempts: 10
        max_velocity_scaling_factor: 1.0
        max_acceleration_scaling_factor: 0.1
        allowed_planning_time: 10.0
        goal_joint_tolerance: 0.0001
        goal_position_tolerance: 0.0001
        goal_orientation_tolerance: 0.0001
        poses_frame_id: "base_link"
        pipeline_name: "ompl"
        planner_id: "RRTConnect"
        #        pipeline_name: "pilz_industrial_motion_planner"
        #        planner_id: "LIN"
        planning_group: "manipulator"
        tool_frame: "tcp"
        distance_threshold: 0.0

      path_1:
        plugin_name: "moveit_reach_plugins/path/CartesianPathGeneration"
        ##########################################################
        ############# PATH PLANNING SPECIFIC PARAMS ##############
        #########################################################
        max_velocity_scaling_factor: 1.0
        max_acceleration_scaling_factor: 0.1
        tool_frame: "tcp"
        max_eef_step: 0.005
        jump_threshold: 0.1 # cca 5 degrees
        #########################################################
        distance_threshold: 0.0 # distance threshold for collision checking
        touch_links: [""]
        global_transformation:
          tx: 0.0
          ty: 0.0
          tz: 0.1
          rx: 0.0   #deg
          ry: 0.0  #deg
          rz: 0.0    #deg
        tool_transformation:
          tx: 0.0
          ty: 0.0
          tz: -0.2
          rx: 0.0   #deg
          ry: 0.0  #deg
          rz: 0.0    #deg

      path_2:
        plugin_name: "moveit_reach_plugins/path/CartesianPathGeneration"
        ##########################################################
        ############# PATH PLANNING SPECIFIC PARAMS ##############
        #########################################################
        max_velocity_scaling_factor: 1.0
        max_acceleration_scaling_factor: 0.1
        tool_frame: "tcp"
        max_eef_step: 0.005
        jump_threshold: 0.1 # cca 5 degrees
        #########################################################
        distance_threshold: 0.0 # distance threshold for collision checking
        touch_links: [""]
        global_transformation:
          tx: 0.0
          ty: 0.0
          tz: 0.0
          rx: 0.0   #deg
          ry: 0.0  #deg
          rz: 0.0    #deg
        tool_transformation:
          tx: 0.0
          ty: 0.0
          tz: 0.05
          rx: 0.0   #deg
          ry: 0.0  #deg
          rz: 0.0    #deg

      path_3:
        plugin_name: "moveit_reach_plugins/path/FreeSpacePathGeneration"
        # end_state is not used when db_goals_are_start==false for first trajectory generation
        # (e.g if FreeSpacePathGeneration was path_1)
        end_state:
          joint_b: -1.7278759594743864
          joint_e: -0.017453292519943295
          joint_l: 1.3264502315156903
          joint_r: 1.2217304763960306
          joint_s: 1.204277
          joint_t: 0.40142572795869574
          joint_u: 1.7627825445142729
        # global and tool transformations are used when no end_state is defined
        # nor is db_goals_are_start==false
        global_transformation:
          tx: 0.0
          ty: 0.0
          tz: 0.0
          rx: 0.0   #deg
          ry: 0.0  #deg
          rz: 0.0    #deg
        tool_transformation:
          tx: 0.0
          ty: 0.0
          tz: 0.0
          rx: 0.0   #deg
          ry: 0.0  #deg
          rz: 0.0    #deg
        touch_links: [ "" ]
        display_motion_plans: false
        publish_planning_requests: false
        num_planning_attempts: 10
        max_velocity_scaling_factor: 1.0
        max_acceleration_scaling_factor: 0.1
        allowed_planning_time: 10.0
        goal_joint_tolerance: 0.0001
        goal_position_tolerance: 0.0001
        goal_orientation_tolerance: 0.0001
        poses_frame_id: "base_link"
        pipeline_name: "ompl"
        planner_id: "RRTConnect"
        #        pipeline_name: "pilz_industrial_motion_planner"
        #        planner_id: "LIN"
        planning_group: "manipulator"
        tool_frame: "tcp"
        distance_threshold: 0.0

      path_4:
        plugin_name: "moveit_reach_plugins/path_generation/CartesianPath"
        global_transformation:
          tx: 0.0
          ty: 0.0
          tz: 0.0
          rx: 0.0   #deg
          ry: 0.0  #deg
          rz: 0.0    #deg
        tool_transformation:
          tx: 0.0
          ty: 0.0
          tz: 0.0
          rx: 0.0   #deg
          ry: 0.0   #deg
          rz: 0.0    #deg
